[package]
name = "rusttest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rand = "0.7.3"


[dependencies.gtk]
package = "gtk4"
version = "0.3.1"
features = ["v4_2"]
